{{- if .Values.target.ssh.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ssh-target
spec:
  selector:
    app: ssh-target
  ports:
  {{- range .Values.target.ssh.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- end }}
{{- end }}