apiVersion: v1
kind: Service
metadata:
  name: boundary-controller
  labels:
    app: boundary-controller
spec:
  type: {{ .Values.boundary.service.type }}
  {{- if eq .Values.boundary.service.type "ClusterIP" }}
  clusterIP: None
  {{- end }}
  selector: 
    app: boundary-controller
  ports:
  {{- range .Values.boundary.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- end }}

