apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.boundary.service.name }}
  labels:
    app: {{ .Values.boundary.service.name }}
spec:
  type: {{ .Values.boundary.service.type }}
  selector: 
    app: boundary-controller
  ports:
  {{- range .Values.boundary.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- end }}

