{{- if and (not .Values.boundary.worker.disableAll) .Values.boundary.worker.ingress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: ingress-worker
  labels:
    app: ingress-worker
spec:
  type: {{ .Values.boundary.service.type }}
  selector: 
    app: ingress-worker
  ports:
  {{- range .Values.boundary.worker.ingress.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- end }}
{{- end }}