{{- if .Values.boundary.worker.ingress.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingress-worker
  labels:
    app: boundary-ingress-worker
spec:
  serviceName: {{ .Values.boundary.worker.ingress.service.name }}
  replicas: 1
  selector:
    matchLabels:
      app: boundary-ingress-worker
  template:
    metadata:
      labels:
        app: boundary-ingress-worker
      annotations:
      {{- toYaml .Values.boundary.podAnnotations | nindent 8 }} 
    spec:
      volumes:
      - name: boundary-ingress-config
        configMap:
          name: ingress-cm
      - name: boundary-logs
        emptyDir: {}
      containers:
      - name: boundary
        {{ if .Values.boundary.image.licenseSecretName }}
        {{ if or (eq .Values.boundary.image.tag "latest") (hasSuffix "-ent" .Values.boundary.image.tag) }}
        image: "{{ .Values.boundary.image.repository }}-enterprise:{{ .Values.boundary.image.tag }}"
        {{ else }}
        image: "{{ .Values.boundary.image.repository }}-enterprise:{{ .Values.boundary.image.tag }}-ent"
        {{ end }}
        {{ else }}
        image: "{{ .Values.boundary.image.repository }}:{{ trimSuffix "-ent" .Values.boundary.image.tag }}"
        {{ end }}
        securityContext:
          runAsUser: 0  # UID
          runAsGroup: 0 # GID
          privileged: true
          fsGroup: 0  
        imagePullPolicy: {{ .Values.boundary.image.pullPolicy }}
        env:
        {{ if .Values.boundary.image.licenseSecretName }}
        - name: BOUNDARY_LICENSE
          valueFrom:
            secretKeyRef:
              name: {{ default "boundary-license" .Values.boundary.image.licenseSecretName }}
              key: {{ default "license" .Values.boundary.image.licenseSecretKey }}
        {{ end }}
        args:
          - "server"
          - "-config"
          - "/boundary/ingress-config.hcl"
        volumeMounts:
        - name: boundary-ingress-config
          mountPath: "/boundary"
        - name: boundary-logs
          mountPath: /var/log/boundary
        ports:
        - containerPort: 9202

{{- end }}