{{- if and (not .Values.boundary.worker.disableAll) .Values.boundary.worker.ingress.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-cm
data:
  ingress-config.hcl: |-
    {{ tpl .Values.boundary.worker.ingress.config . | nindent 4 | trim }}
{{- end }}
