{{- if and (not .Values.boundary.worker.disableAll) .Values.boundary.worker.intermediate.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: intermediate-worker
  labels:
    app: boundary-intermediate-worker
spec:
  serviceName: intermediate-worker
  replicas: {{ .Values.boundary.worker.intermediate.replicas }}
  selector:
    matchLabels:
      app: boundary-intermediate-worker
  template:
    metadata:
      labels:
        app: boundary-intermediate-worker
      annotations:
      {{- toYaml .Values.boundary.podAnnotations | nindent 8 }} 
    spec:
      volumes:
      - name: boundary-intermediate-config
        configMap:
          name: intermediate-cm
      - name: boundary-logs
        emptyDir: {}
      containers:
      - name: boundary
        {{ if .Values.boundary.image.licenseSecretName }}
        {{ if or (eq .Values.boundary.image.tag "latest") (hasSuffix "-ent" .Values.boundary.image.tag) }}
        image: "{{ .Values.boundary.image.repository }}-enterprise:{{ .Values.boundary.image.tag }}"
        {{ else }}
        image: "{{ .Values.boundary.image.repository }}-enterprise:{{ .Values.boundary.image.tag }}-ent"
        {{ end }}
        {{ else }}
        image: "{{ .Values.boundary.image.repository }}:{{ trimSuffix "-ent" .Values.boundary.image.tag }}"
        {{ end }}
        imagePullPolicy: {{ .Values.boundary.image.pullPolicy }}
        env:
        {{ if .Values.boundary.image.licenseSecretName }}
        - name: BOUNDARY_LICENSE
          valueFrom:
            secretKeyRef:
              name: {{ default "boundary-license" .Values.boundary.image.licenseSecretName }}
              key: {{ default "license" .Values.boundary.image.licenseSecretKey }}
        {{ end }}
        args:
          - "server"
          - "-config"
          - "/boundary/intermediate-config.hcl"
        volumeMounts:
        - name: boundary-intermediate-config
          mountPath: "/boundary"
        - name: boundary-logs
          mountPath: /var/log/boundary
        ports:
        - containerPort: 9202

{{- end }}