{{- if and (not .Values.boundary.worker.disableAll) .Values.boundary.worker.intermediate.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: intermediate-worker
  labels:
    app: intermediate-worker
spec:
  clusterIP: None
  type: {{ .Values.boundary.service.type }}
  selector: 
    app: intermediate-worker
  ports:
  {{- range .Values.boundary.worker.ingress.service.ports }}
  - name: {{ .name }}
    port: {{ .port }}
    targetPort: {{ .port }}
  {{- end }}
{{- end }}