apiVersion: v1
kind: Service
metadata:
  name: postgres-boundary
  labels:
    app: postgres-boundary
spec:
  type: ClusterIP
  selector:
    app: postgres-boundary
  ports:
  - port: 5432
    targetPort: 5432