apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres-boundary
spec:
  type: ClusterIP
  selector:
    app: postgres-boundary
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}