{{- if .Values.boundary.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "boundary.serviceAccountName" . }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
  {{- with .Values.boundary.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
